# Generated by Django 6.0.6 on 2026-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='720p', max_length=20),
        ),
    ]
