# Generated by Django 6.0.6 on 2026-07-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_options_video_category_video_resolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
