# Generated by Django 6.0.6 on 2026-08-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_rename_thumbnail_video_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
