# Generated by Django 6.0.6 on 2026-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_rename_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=20, null=True),
        ),
    ]
